name: Kolhapur Property Agent

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Kolhapur Property Agent is running."
